image: node:14
cache:
  paths:
    - node_modules/
    - .cache/
    - public/
pages:
  script:
    - yarn
    - yarn build-storybook
  artifacts:
    paths:
      - storybook-static
  only:
    - main
