image: node:14
cache:
  paths:
    - node_modules/
    - .cache/
    - public/
pages:
  script:
    - yarn
    - yarn build-storybook
    - cd ../
    - cp -R ./page ./storybook-static
  artifacts:
    paths:
      - public
  only:
    - main
